spring:
  datasource:
    url: jdbc:postgresql://PLACEHOLDER1:5432/dev-finder
    username: PLACEHOLDER
    password: PLACEHOLDER
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      maximum-pool-size: 50
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  redis:
    ssl: true
    host: PLACEHOLDER
    password: PLACEHOLDER
    cluster:
      nodes:
        - PLACEHOLDER:7000
        - PLACEHOLDER:7001
        - PLACEHOLDER:7002
        - PLACEHOLDER:7003
        - PLACEHOLDER:7004
        - PLACEHOLDER:7005
