spring:
  datasource:
    url: jdbc:postgresql://173.18.0.11:5432/dev-finder
    username: dev-finder
    password: ☺♠↔•◘○◙♀♂♪►◄↕‼¶§→☻∟▲
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      maximum-pool-size: 50
  #  sql:
#    init:
#      mode: always
#      platform: postgresql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  redis:
    ssl: false
    cluster:
      nodes:
        - 173.18.0.2:7000
        - 173.18.0.3:7001
        - 173.18.0.4:7002
        - 173.18.0.5:7003
        - 173.18.0.6:7004
        - 173.18.0.7:7005