server:
  servlet:
    context-path: /api
    session:
      timeout: 300
  max-http-header-size: 10000000
  compression:
    enabled: true
    mime-types:
      - text/html,text/xml,text/plain,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  profiles:
    active: prod
  cache:
    type: simple
  main:
    allow-bean-definition-overriding: true
    web-application-type: SERVLET
  web:
    resources:
      chain:
        enabled: true
        cache: true
      add-mappings: true
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


info:
  app:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - env
          - httptrace
          - shutdown
          - loggers
          - health
          - prometheus
          - heapdump
          - threaddump
          - metrics
          - logfile
          - scheduledtasks
          - caches
          - configprops
          - startup
          - mappings
          - prometheus
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    sessions:
      enabled: true
    httptrace:
      enabled: true
    shutdown:
      enabled: true
    loggers:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    heapdump:
      enabled: true
    threaddump:
      enabled: true
    metrics:
      enabled: true
      cache:
        time-to-live: 10000
    logfile:
      enabled: true
    scheduledtasks:
      enabled: true
      cache:
        time-to-live: 10000
    startup:
      enabled: true
      cache:
        time-to-live: 10000
    mappings:
      enabled: true
      cache:
        time-to-live: 10000
    prometheus:
      enabled: true
  trace:
    http:
      enabled: true
      #     org.springframework.boot.actuate.trace.http.Include
      include:
        - REQUEST_HEADERS
        - RESPONSE_HEADERS
        - COOKIE_HEADERS
        - AUTHORIZATION_HEADER
        - PRINCIPAL
        - REMOTE_ADDRESS
        - TIME_TAKEN

LOGS_FOLDER: ./logs/${spring.profiles.active}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,America/Recife
  charset:
    file: ISO-8859-1
    console: ISO-8859-1
  file:
    path: ${LOGS_FOLDER}
    name: ${LOGS_FOLDER}/dev-finder.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd,America/Recife}.%i.log
      max-file-size:  512MB
      total-size-cap: 40GB
      max-history: 32
    triggeringpolicy:
      max-file-size: 512MB
    com:
      edug:
        devfinder:
          configs:
            HttpLoggingInterceptor: TRACE
            HttpLoggingFilter: TRACE
springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs